# Generated by Django 4.2.4 on 2023-08-26 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.EmailField(max_length=254)),
                ('reciever', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opened_time_diff', models.DateTimeField(null=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sendmail')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
