# Generated by Django 4.2.4 on 2023-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sendmail_trackmail_delete_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmail',
            name='opened_time_diff',
            field=models.TimeField(null=True),
        ),
    ]
